---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bonkey
  namespace: bonkey-app
  labels:
    app: bonkey
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bonkey
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 1
