---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bonkey-storage
  namespace: bonkey-app
  labels:
    app: bonkey
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti
