---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bonkey-storage
  namespace: bonkey-app
  labels:
    app: bonkey
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
